# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_os_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='os_favorite',
            new_name='is_favorite',
        ),
    ]
